In [1]:
import pandas as pd
import numpy as np
import os
from sklearn.preprocessing import MinMaxScaler

In [2]:
df = pd.read_csv('../data/covertype/original/covtype.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 581012 entries, 0 to 581011
Data columns (total 55 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   0           581012 non-null  int64
 1   1           581012 non-null  int64
 2   2           581012 non-null  int64
 3   3           581012 non-null  int64
 4   4           581012 non-null  int64
 5   5           581012 non-null  int64
 6   6           581012 non-null  int64
 7   7           581012 non-null  int64
 8   8           581012 non-null  int64
 9   9           581012 non-null  int64
 10  10          581012 non-null  int64
 11  11          581012 non-null  int64
 12  12          581012 non-null  int64
 13  13          581012 non-null  int64
 14  14          581012 non-null  int64
 15  15          581012 non-null  int64
 16  16          581012 non-null  int64
 17  17          581012 non-null  int64
 18  18          581012 non-null  int64
 19  19          581012 non-null  int64
 20  20          581012 non-null  int64
 21  21          581012 non-null  int64
 22  22          581012 non-null  int64
 23  23          581012 non-null  int64
 24  24          581012 non-null  int64
 25  25          581012 non-null  int64
 26  26          581012 non-null  int64
 27  27          581012 non-null  int64
 28  28          581012 non-null  int64
 29  29          581012 non-null  int64
 30  30          581012 non-null  int64
 31  31          581012 non-null  int64
 32  32          581012 non-null  int64
 33  33          581012 non-null  int64
 34  34          581012 non-null  int64
 35  35          581012 non-null  int64
 36  36          581012 non-null  int64
 37  37          581012 non-null  int64
 38  38          581012 non-null  int64
 39  39          581012 non-null  int64
 40  40          581012 non-null  int64
 41  41          581012 non-null  int64
 42  42          581012 non-null  int64
 43  43          581012 non-null  int64
 44  44          581012 non-null  int64
 45  45          581012 non-null  int64
 46  46          581012 non-null  int64
 47  47          581012 non-null  int64
 48  48          581012 non-null  int64
 49  49          581012 non-null  int64
 50  50          581012 non-null  int64
 51  51          581012 non-null  int64
 52  52          581012 non-null  int64
 53  53          581012 non-null  int64
 54  Cover_Type  581012 non-null  int64
dtypes: int64(55)
memory usage: 243.8 MB

In [4]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,45,46,47,48,49,50,51,52,53,Cover_Type
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,5
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,5
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,2
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,2
4,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,5

In [5]:
df['Cover_Type'] = df['Cover_Type'].astype(int)

In [6]:
len(df.columns)

55

In [7]:
df.drop(df.columns[10:-1], axis=1, inplace=True)

In [8]:
df

           0    1   2    3    4     5    6    7    8     9  Cover_Type
0       2596   51   3  258    0   510  221  232  148  6279           5
1       2590   56   2  212   -6   390  220  235  151  6225           5
2       2804  139   9  268   65  3180  234  238  135  6121           2
3       2785  155  18  242  118  3090  238  238  122  6211           2
4       2595   45   2  153   -1   391  220  234  150  6172           5
...      ...  ...  ..  ...  ...   ...  ...  ...  ...   ...         ...
581007  2396  153  20   85   17   108  240  237  118   837           3
581008  2391  152  19   67   12    95  240  237  119   845           3
581009  2386  159  17   60    7    90  236  241  130   854           3
581010  2384  170  15   60    5    90  230  245  143   864           3
581011  2383  165  13   60    4    67  231  244  141   875           3

[581012 rows x 11 columns]

In [9]:
df['timestamps'] = list(range(1, df.shape[0]+1))

In [10]:
df

,0,1,2,3,4,5,6,7,8,9,Cover_Type,timestamps
0,2596,51,3,258,0,510,221,232,148,6279,5,1
1,2590,56,2,212,-6,390,220,235,151,6225,5,2
2,2804,139,9,268,65,3180,234,238,135,6121,2,3
3,2785,155,18,242,118,3090,238,238,122,6211,2,4
4,2595,45,2,153,-1,391,220,234,150,6172,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...
581007,2396,153,20,85,17,108,240,237,118,837,3,581008
581008,2391,152,19,67,12,95,240,237,119,845,3,581009
581009,2386,159,17,60,7,90,236,241,130,854,3,581010
581010,2384,170,15,60,5,90,230,245,143,864,3,581011
581011,2383,165,13,60,4,67,231,244,141,875,3,581012

In [11]:
scaler = MinMaxScaler()
target = df['Cover_Type']
timestamps = df['timestamps']
columns = df.columns
df = pd.DataFrame(scaler.fit_transform(df.drop(['Cover_Type', 'timestamps'], axis=1).values), columns=columns[0:-2])
df

,0,1,2,3,4,5,6,7,8,9
0,0.368684,0.141667,0.045455,0.184681,0.223514,0.071659,0.870079,0.913386,0.582677,0.875366
1,0.365683,0.155556,0.030303,0.151754,0.215762,0.054798,0.866142,0.925197,0.594488,0.867838
2,0.472736,0.386111,0.136364,0.191840,0.307494,0.446817,0.921260,0.937008,0.531496,0.853339
3,0.463232,0.430556,0.272727,0.173228,0.375969,0.434172,0.937008,0.937008,0.480315,0.865886
4,0.368184,0.125000,0.030303,0.109520,0.222222,0.054939,0.866142,0.921260,0.590551,0.860449
...,...,...,...,...,...,...,...,...,...,...
581007,0.268634,0.425000,0.303030,0.060845,0.245478,0.015175,0.944882,0.933071,0.464567,0.116688
581008,0.266133,0.422222,0.287879,0.047960,0.239018,0.013348,0.944882,0.933071,0.468504,0.117803
581009,0.263632,0.441667,0.257576,0.042949,0.232558,0.012646,0.929134,0.948819,0.511811,0.119058
581010,0.262631,0.472222,0.227273,0.042949,0.229974,0.012646,0.905512,0.964567,0.562992,0.120452
581011,0.262131,0.458333,0.196970,0.042949,0.228682,0.009414,0.909449,0.960630,0.555118,0.121985

In [12]:
df['timestamps'] = timestamps
df['cluster'] = target

In [13]:
path = '../data/covertype/preprocessed'

df_split = np.array_split(df, 50)

for i, part in enumerate(df_split):
    part.to_csv(os.path.join(path, f'covertype_{i}.csv'), index=False)

/home/codespace/.local/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)