In [1]:
import pandas as pd
import numpy as np
import os
from sklearn.preprocessing import MinMaxScaler

In [2]:
df = pd.read_csv('../data/kddcup/original/kddcup.data_10_percent.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 494021 entries, 0 to 494020
Data columns (total 42 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   duration                     494021 non-null  int64
 1   protocol_type                494021 non-null  object
 2   service                      494021 non-null  object
 3   flag                         494021 non-null  object
 4   src_bytes                    494021 non-null  int64
 5   dst_bytes                    494021 non-null  int64
 6   land                         494021 non-null  int64
 7   wrong_fragment               494021 non-null  int64
 8   urgent                       494021 non-null  int64
 9   hot                          494021 non-null  int64
 10  num_failed_logins            494021 non-null  int64
 11  logged_in                    494021 non-null  int64
 12  num_compromised              494021 non-null  int64
 13  root_shell                   494021 non-null  int64
 14  su_attempted                 494021 non-null  int64
 15  num_root                     494021 non-null  int64
 16  num_file_creations           494021 non-null  int64
 17  num_shells                   494021 non-null  int64
 18  num_access_files             494021 non-null  int64
 19  num_outbound_cmds            494021 non-null  int64
 20  is_host_login                494021 non-null  int64
 21  is_guest_login               494021 non-null  int64
 22  count                        494021 non-null  int64
 23  srv_count                    494021 non-null  int64
 24  serror_rate                  494021 non-null  float64
 25  srv_serror_rate              494021 non-null  float64
 26  rerror_rate                  494021 non-null  float64
 27  srv_rerror_rate              494021 non-null  float64
 28  same_srv_rate                494021 non-null  float64
 29  diff_srv_rate                494021 non-null  float64
 30  srv_diff_host_rate           494021 non-null  float64
 31  dst_host_count               494021 non-null  int64
 32  dst_host_srv_count           494021 non-null  int64
 33  dst_host_same_srv_rate       494021 non-null  float64
 34  dst_host_diff_srv_rate       494021 non-null  float64
 35  dst_host_same_src_port_rate  494021 non-null  float64
 36  dst_host_srv_diff_host_rate  494021 non-null  float64
 37  dst_host_serror_rate         494021 non-null  float64
 38  dst_host_srv_serror_rate     494021 non-null  float64
 39  dst_host_rerror_rate         494021 non-null  float64
 40  dst_host_srv_rerror_rate     494021 non-null  float64
 41  target                       494021 non-null  object
dtypes: float64(15), int64(23), object(4)
memory usage: 158.3+ MB

In [4]:
df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,target
0,0,tcp,http,SF,181,5450,0,0,0,0,...,9,1.0,0.0,0.11,0.0,0.0,0.0,0.0,0.0,normal.
1,0,tcp,http,SF,239,486,0,0,0,0,...,19,1.0,0.0,0.05,0.0,0.0,0.0,0.0,0.0,normal.
2,0,tcp,http,SF,235,1337,0,0,0,0,...,29,1.0,0.0,0.03,0.0,0.0,0.0,0.0,0.0,normal.
3,0,tcp,http,SF,219,1337,0,0,0,0,...,39,1.0,0.0,0.03,0.0,0.0,0.0,0.0,0.0,normal.
4,0,tcp,http,SF,217,2032,0,0,0,0,...,49,1.0,0.0,0.02,0.0,0.0,0.0,0.0,0.0,normal.

In [5]:
df = df[['duration',
'src_bytes',
'dst_bytes',
'wrong_fragment',
'urgent',
'hot',
'num_failed_logins',
'num_compromised',
'root_shell',
'su_attempted',
'num_root',
'num_file_creations',
'num_shells',
'num_access_files',
'num_outbound_cmds',
'count',
'srv_count',
'serror_rate',
'srv_serror_rate',
'rerror_rate',
'srv_rerror_rate',
'same_srv_rate',
'diff_srv_rate',
'srv_diff_host_rate',
'dst_host_count',
'dst_host_srv_count',
'dst_host_same_srv_rate',
'dst_host_diff_srv_rate',
'dst_host_same_src_port_rate',
'dst_host_srv_diff_host_rate',
'dst_host_serror_rate',
'dst_host_srv_serror_rate',
'dst_host_rerror_rate',
'dst_host_srv_rerror_rate','target']]

In [6]:
df

,duration,src_bytes,dst_bytes,wrong_fragment,urgent,hot,num_failed_logins,num_compromised,root_shell,su_attempted,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,target
0,0,181,5450,0,0,0,0,0,0,0,...,9,1.0,0.0,0.11,0.00,0.00,0.00,0.0,0.0,normal.
1,0,239,486,0,0,0,0,0,0,0,...,19,1.0,0.0,0.05,0.00,0.00,0.00,0.0,0.0,normal.
2,0,235,1337,0,0,0,0,0,0,0,...,29,1.0,0.0,0.03,0.00,0.00,0.00,0.0,0.0,normal.
3,0,219,1337,0,0,0,0,0,0,0,...,39,1.0,0.0,0.03,0.00,0.00,0.00,0.0,0.0,normal.
4,0,217,2032,0,0,0,0,0,0,0,...,49,1.0,0.0,0.02,0.00,0.00,0.00,0.0,0.0,normal.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494016,0,310,1881,0,0,0,0,0,0,0,...,255,1.0,0.0,0.01,0.05,0.00,0.01,0.0,0.0,normal.
494017,0,282,2286,0,0,0,0,0,0,0,...,255,1.0,0.0,0.17,0.05,0.00,0.01,0.0,0.0,normal.
494018,0,203,1200,0,0,0,0,0,0,0,...,255,1.0,0.0,0.06,0.05,0.06,0.01,0.0,0.0,normal.
494019,0,291,1200,0,0,0,0,0,0,0,...,255,1.0,0.0,0.04,0.05,0.04,0.01,0.0,0.0,normal.
494020,0,219,1234,0,0,0,0,0,0,0,...,255,1.0,0.0,0.17,0.05,0.00,0.01,0.0,0.0,normal.

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit(df['target'].unique())
target = le.transform(df['target'])

In [8]:
df['target'] = target

In [9]:
df

,duration,src_bytes,dst_bytes,wrong_fragment,urgent,hot,num_failed_logins,num_compromised,root_shell,su_attempted,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,target
0,0,181,5450,0,0,0,0,0,0,0,...,9,1.0,0.0,0.11,0.00,0.00,0.00,0.0,0.0,11
1,0,239,486,0,0,0,0,0,0,0,...,19,1.0,0.0,0.05,0.00,0.00,0.00,0.0,0.0,11
2,0,235,1337,0,0,0,0,0,0,0,...,29,1.0,0.0,0.03,0.00,0.00,0.00,0.0,0.0,11
3,0,219,1337,0,0,0,0,0,0,0,...,39,1.0,0.0,0.03,0.00,0.00,0.00,0.0,0.0,11
4,0,217,2032,0,0,0,0,0,0,0,...,49,1.0,0.0,0.02,0.00,0.00,0.00,0.0,0.0,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494016,0,310,1881,0,0,0,0,0,0,0,...,255,1.0,0.0,0.01,0.05,0.00,0.01,0.0,0.0,11
494017,0,282,2286,0,0,0,0,0,0,0,...,255,1.0,0.0,0.17,0.05,0.00,0.01,0.0,0.0,11
494018,0,203,1200,0,0,0,0,0,0,0,...,255,1.0,0.0,0.06,0.05,0.06,0.01,0.0,0.0,11
494019,0,291,1200,0,0,0,0,0,0,0,...,255,1.0,0.0,0.04,0.05,0.04,0.01,0.0,0.0,11
494020,0,219,1234,0,0,0,0,0,0,0,...,255,1.0,0.0,0.17,0.05,0.00,0.01,0.0,0.0,11

In [10]:
df['timestamps']= list(range(1, df.shape[0]+1))

In [11]:
scaler = MinMaxScaler()
target = df['target']
timestamps = df['timestamps']
columns = df.columns
df = pd.DataFrame(scaler.fit_transform(df.drop(['target', 'timestamps'], axis=1).values), columns=columns[0:-2])
df

,duration,src_bytes,dst_bytes,wrong_fragment,urgent,hot,num_failed_logins,num_compromised,root_shell,su_attempted,...,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate
0,0.0,2.610418e-07,0.001057,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.035294,0.035294,1.0,0.0,0.11,0.00,0.00,0.00,0.0,0.0
1,0.0,3.446905e-07,0.000094,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.074510,0.074510,1.0,0.0,0.05,0.00,0.00,0.00,0.0,0.0
2,0.0,3.389216e-07,0.000259,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.113725,0.113725,1.0,0.0,0.03,0.00,0.00,0.00,0.0,0.0
3,0.0,3.158461e-07,0.000259,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.152941,0.152941,1.0,0.0,0.03,0.00,0.00,0.00,0.0,0.0
4,0.0,3.129617e-07,0.000394,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.192157,0.192157,1.0,0.0,0.02,0.00,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494016,0.0,4.470881e-07,0.000365,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.337255,1.000000,1.0,0.0,0.01,0.05,0.00,0.01,0.0,0.0
494017,0.0,4.067060e-07,0.000443,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.023529,1.000000,1.0,0.0,0.17,0.05,0.00,0.01,0.0,0.0
494018,0.0,2.927706e-07,0.000233,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.062745,1.000000,1.0,0.0,0.06,0.05,0.06,0.01,0.0,0.0
494019,0.0,4.196859e-07,0.000233,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.101961,1.000000,1.0,0.0,0.04,0.05,0.04,0.01,0.0,0.0
494020,0.0,3.158461e-07,0.000239,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.023529,1.000000,1.0,0.0,0.17,0.05,0.00,0.01,0.0,0.0

In [12]:
df['timestamps'] = timestamps
df['cluster'] = target

In [13]:
df.to_csv('../data/kddcup/preprocessed/kddcup.csv', index=False)

In [14]:
path = '../data/kddcup/preprocessed'

df_split = np.array_split(df, 12)

for i, part in enumerate(df_split):
    part.to_csv(os.path.join(path, f'kddcup_{i}.csv'), index=False)

In [30]:
window_size = 48
expname = 'kddcup'
df = pd.read_csv(f"/root/EdgeCluster/results/{expname}/tabular/{window_size}/final_clustering.csv")

KeyboardInterrupt:

In [ ]:
df[(df['cluster']==-2)].shape

(4, 40)

In [ ]:
df.shape

(494021, 40)